noisepy/NoisePy

src/noise_module.py
I added the ability in `**preprocess_raw()**` to get `rm_resp_out` from the  use, specified in `preproc_para`. The original version hard-coded 'VEL', which may cause some issue when the user wants to get other output. I have made the corresponding updates in the `S0A_download_ASDF_MPI.py` script for my local copy, not uploaded here. I can change the master branch on that if you want.
The GitHub comparison marks a lot of places I didn't change (actually they are only some space related differences). 
Thanks,
Xiaotao
=> Response output specified by the user

src/plotting_modules.py
Hello,
this pull request suggest some changes to fix various minor bugs I encountered in the plotting module, namely when more than one stacking methods are saved in the h5 files, a bug with y tick labels, etc. I also added some keyword argument for figsize and max inter-station distance too. 
Cheers,
Genevieve
=> Fix various bugs in plotting module

.github/workflows/test.yaml, README.md, src/S1_fft_cc_MPI.py, src/noisepy.py
- Add `noisepy.py cross_correlate` command
- Update README accordingly
- Add S1 (`cross_correlate`) as part of the branch merging tests
- No functional changes to `src/S1_fft_cc_MPI.py`, mostly just moving all the functionality into a function to be called from `noisepy.py`
=> Add cross-correlate command (S1) and include it as part of the branch testing

.github/actions/setup/action.yaml, .github/workflows/test.yaml, README.md, src/S1_fft_cc_MPI.py, src/S2_stacking.py, src/noisepy.py
As noted in the README, this PR adds the `stack` cmd:
```
usage: noisepy.py stack [-h] [--path PATH] --method
{linear,pws,robust,nroot,selective,auto_covariance,all}
optional arguments:
-h, --help            show this help message and exit
--path PATH           Directory to look for input files (default:
/Users/carlosg/Documents/SCAL)
--method {linear,pws,robust,nroot,selective,auto_covariance,all}
Stacking method (default: None)
```
It also adds this step into the verification tests.
=> Add stacking to noisepy.py and as part of merge tests

.vscode/settings.json, README.md
- Instructions on how to setup pre-commit locally
- Recommended VS Code extensions and corresponding settings to auto-format on save
=> README and vscode settings for pre-commit checks

src/noisepy/seis/main.py
Add a command to the CLI that allows running the 3 steps (`download`, `cross_correlate` and `stack`) in a single call. E.g.
```
noisepy all --start 2019_02_01_00_00_00 --end 2019_02_01_01_00_00 --stations ARV,BAK --inc_hours 1 --path ~/tmp --freq_norm rma --method linear
```
=> Add 'all' command to the CLI

.github/workflows/release.yaml, .gitignore, pyproject.toml, src/noisepy/seis/__init__.py
Using [hatch-vcs](https://github.com/ofek/hatch-vcs)
Test run: https://github.com/mdenolle/NoisePy/actions/runs/4887451147
=> Generate version from git tags

.github/workflows/test.yaml, pyproject.toml
Also expand the testing to run on both python 3.8 and 3.11
=> Upgrade to numba 0.57 to be able to run on python >3.10

tutorials/get_started.ipynb
this corrects the text of the get_started tutorial and demonstrates the configuration for noisepy in general.. and Hey, this one works!
=> update the easy tutorial

src/noisepy/seis/S0A_download_ASDF_MPI.py, src/noisepy/seis/datatypes.py, tutorials/get_started.ipynb
=> Fix 144: move client_url_key to ConfigParameters

.github/workflows/test.yaml, src/noisepy/seis/S0A_download_ASDF_MPI.py, src/noisepy/seis/S1_fft_cc_MPI.py, src/noisepy/seis/main.py, tutorials/cli/README.md
This PR builds on #147 to add back support for MPI in the cross-correlation step.
=> Support using MPI for CC

pyproject.toml, src/noisepy/seis/datatypes.py, src/noisepy/seis/main.py, tests/test_datatypes.py
`pydantic-yaml` has released 1.0 and it has some breaking changes.
=> Upgrade to pydantic 2.0 and pydantic-yaml 1.0.0

src/noisepy/seis/S1_fft_cc_MPI.py, src/noisepy/seis/asdfstore.py, src/noisepy/seis/zarrstore.py
A few checks to make the code robust to missing data
=> Make frequency filtering robust to missing data

.github/workflows/precommit.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, pyproject.toml, src/noisepy/seis/S1_fft_cc_MPI.py, src/noisepy/seis/S2_stacking.py, src/noisepy/seis/asdfstore.py, src/noisepy/seis/main.py, src/noisepy/seis/plotting_modules.py, src/noisepy/seis/utils.py, src/noisepy/seis/zarrstore.py, tests/test_ccstores.py, tests/test_cli.sh, tests/test_stackstores.py
Refactored some common functionality into a `ZarrStoreHelper` which is used by `ZarrCCStore` and `ZarrStackStore`
=> Implement ZarrStackStore

src/noisepy/seis/S1_fft_cc_MPI.py, src/noisepy/seis/S2_stacking.py, src/noisepy/seis/main.py, src/noisepy/seis/utils.py, tests/test_cli.sh, tutorials/get_started.ipynb, tutorials/noisepy_pnwstore_tutorial.ipynb, tutorials/noisepy_scedc_tutorial.ipynb
Tested with the following parameters:
```
STATIONS=ADO,ALP,ARV,AVM,BAK,BAR,BBR,BBS,BC3,BCW
START=2019-02-01T00:00:00
END=2019-02-05T00:00:00
INC_HOURS=24
```
Total stacking time went down from `173.19s` to `26.86`.
=> Parallelize stacking

CONTRIBUTING.md, tests/test_cli.sh
Also fix the format parameter check in test_cli.sh
=> Add testing instructions to CONTRIBUTING.md

README.md
This PR adds a small contributing section in the README.md
=> docs: add contributing section to README

.vscode/launch.json, README.md, src/noisepy/seis/S1_fft_cc_MPI.py, src/noisepy/seis/S2_stacking.py, src/noisepy/seis/scedc_s3store.py
Main change is to `src/noisepy/seis/S1_fft_cc_MPI.py` + a couple of small fixes
=> feat(S1): Allow filtering of channel pairs

src/noisepy/seis/scedc_s3store.py
The SCEDC store eagerly loaded all channels for all timespans at the beginning, which can be efficient on a single node. However, when work is distributed over MPI or AWS Batch, the nodes end up loading the channel list for all timespans, instead of only the ones they'll work on. 
This PR changes this by deferring the loading of channels until they are requested.
=> (fix) SCEDC store: Only load required channels

Dockerfile, Dockerfile.dev, pyproject.toml, script/docker_dev.sh, script/gen_req.py
- Simplified docker build by using python base image. Since MPI is now optional and not used in cloud deployments the build is much simpler
- Added scripts and docker file for building and publishing from a local repo during development (for fast iteration on AWS)
=> Improvements to docker publishing

tutorials/noisepy_datastore.ipynb
This PR add a notebook that leads users go through the SCEDCS3DataStore class
=> Add datastore notebook

src/noisepy/seis/scedc_s3store.py
Allow something like this:
channel_filter("*", "BH,EH")
=> Allow all station filter

.github/actions/setup/action.yaml, .github/workflows/test.yaml, README.md, codecov.yml, pyproject.toml
This PR updates the codecov wit current tests. Currently, the code coverage is about ~51%. We will add more tests to increase the coverage.
=> Update codecov in CI

src/noisepy/seis/utils.py, tutorials/requirements.txt
=> Improve display of progress bar in notebooks

CODE_OF_CONDUCT.md, src/noisepy/seis/scedc_s3store.py, tests/test_scedc_s3store.py
=> Fix: parsing scedc filename dates

.github/workflows/test.yaml
Avoid depending on the FDSN download service, which is often flaky
=> Integration tests using SCEDC S3 data

.vscode/launch.json, CONTRIBUTING.md, README.md, integration_tests/cc_stack_test.py, src/noisepy/seis/datatypes.py, src/noisepy/seis/stack.py
- Fix stacking when `keep_substacks=True`
- Bump coverage in `stack.py` from 66% to 89%
- Fix typo in station name 🤦
=> Fixes and test coverage for stacking

src/noisepy/seis/plotting_modules.py, tutorials/get_started.ipynb
https://github.com/uw-ssec/codeuw/issues/33
=> refactor: update plot_waveform() to use the (ASDF)RawDataStore

src/noisepy/monitoring/monitoring_utils.py, tests/test_monitoring_utils.py
This PR adds unit tests for the  monitoring utils module.
Fix #251
=> chore: add monitoring unit tests

pyproject.toml, script/additional_modules/core_functions.py, src/noisepy/monitoring/monitoring_methods.py, tutorials/README.md, tutorials/_config.yml, tutorials/_toc.yml, tutorials/old/dvv_module.py, tutorials/tutorial_local_mseed.ipynb, tutorials/tutorial_pnwstore.ipynb
- Add tutorial for local mSEED store
- Fix #330
=> feat: add local mSEED tutorial

.github/workflows/notebooks.yml, .github/workflows/precommit.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, src/noisepy/functions_2019/noise_module.py, src/noisepy/seis/noise_module.py, tests/test_to_comp_stacking.py
- Fix #332: The selective stacking was accidentally missing in the current version. Thanks @koepflma for pointing this out.
- Update the git action version
=> feat: add selective stacking

src/noisepy/seis/noise_module.py, tests/test_noise_module.py, tests/test_stack.py
Update sanity check for those streams with fluctuated sampling rate (due to digitizer issue). Resample if sampling rate mismatch.
Fix #334
=> fix: check sampling rate or resample
