noisepy/NoisePy

- src/S0B_to_ASDF.py
- src/noise_module.py
Hi, 
hope it's okay to suggest code changes with a pull request. There is a bug when using S0B and choosing to read StationXML response from a directory. In stats2inv(), since glob.glob() returns a list, L292 and 293 in noise_module fail. In preprocess_raw() I added a check on if the response is empty (which previously happened when stats2inv failed to read the response from staxml). Also moved the check on empty data in S0B (lines 208-210) earlier because it tr is empty, there will be an indexing error raised at Line 204.
Thanks for making NoisePy available to the community! It's very useful for my work.
Genevieve
> Fix bug when reading of staxml from a directory

- src/noise_module.py
- test/test_whiten.py
Hi developers,
when I recently looked in detail at the whitening routine from NoisePy, I noticed that the tapered section is tapered separately from the whitened section of the input spectrum.
This has no consequence for the case where phase-only is chosen, because the amplitude of the main section is 1 and the amplitude of the taper where it connects to the main (untapered) part of the spectrum is also 1. However, for the case where spectral smoothing is used, this may introduce a jump in the fourier amplitude spectrum that may lead to high-frequency artefacts in the time-domain output.
I created an updated routine. This may have to be edited (for example, I used numpy rfftn rather than scipy). I also added a test to check that at least in the part where the signals are expected to be …
> Whitening update

- .github/workflows/test.yaml
- src/S0A_download_ASDF_MPI.py
- src/noisepy.py
The goal of this PR is to enable CI testing of the download step (other steps to follow). The main change is the addition of a command line interface (CLI) and a small refactoring of ```S0A_download_ASDF_MPI.py``` to allow the CLI to call it. With this change, it's easier to execute the steps by passing arguments on the command line instead of changing the code. E.g.:
```
usage: noisepy.py download [-h] [--path PATH] --start START --end END
[--stations STATIONS] [--channels CHANNELS]
[--inc_hours INC_HOURS]
optional arguments:
-h, --help            show this help message and exit
--path PATH           Directory for downloading files
--start START         Start date in the format: %Y_%m_%d_%H_%M_%S
--end END             End date in the format: %Y_%m_%d_%H_%M_%S
--stations STATIONS   Comma …
```
> CLI entry point and download step testing during CI

- README.md
- src/S0A_download_ASDF_MPI.py
- src/noisepy.py
- Remove `S0A_download_ASDF_MPI.py` as an entry point
- Update README to use the new entry point and to use `requirements.txt` for installation
- Moved defaults to the CLI and display them in the help text:
```
usage: noisepy.py download [-h] [--path PATH] --start START --end END
[--stations STATIONS] [--channels CHANNELS]
[--inc_hours INC_HOURS]
optional arguments:
-h, --help            show this help message and exit
--path PATH           Directory for downloading files (default:
/Users/carlosg/Documents/SCAL)
--start START         Start date in the format: %Y_%m_%d_%H_%M_%S (default:
2016_07_01_0_0_0)
--end END             End date in the format: %Y_%m_%d_%H_%M_%S (default:
2016_07_02_0_0_0)
--stations STATIONS   Comma separated list of stations or '*' for all
(default: *)
--channels …
```
> Update tutorial to use requirements.txt and noisepy.py

- Dockerfile
Allows for running noisepy via container. E.g:
```
$ docker run noisepy
usage: noisepy.py [-h] {download,cross_correlate,stack} ...
positional arguments:
{download,cross_correlate,stack}
options:
-h, --help            show this help message and exit
```
By mapping a volume (**-v**) it can be used to download/process data in the local file system. E.g.
```
mkdir ./tmp
docker run -v ./tmp:/tmp noisepy download \
--start 2019_02_01_00_00_00 \
--end 2019_02_01_01_00_00 \
--stations ARV,BAK \
--inc_hours 1 \
--path /tmp
```
> Add Dockerfile for building container for noisepy

- .github/CODEOWNERS
- .github/workflows/release.yaml
This PR adds a workflow that builds and pushes a noisepy container when a release is created. Here's the package from a test run: https://github.com/mdenolle?tab=packages.
The container can be run as follows (e.g. for the `cross_correlate` step, assuming data is in the local `~/tmp` directory):
```
docker run -v ~/tmp:/tmp ghcr.io/mdenolle/noisepy:latest cross_correlate --path /tmp
```
> Add release workflow for container

- src/S0A_download_ASDF_MPI.py
- src/S0B_to_ASDF.py
- src/S1_fft_cc_MPI.py
- src/S2_stacking.py
- src/plotting_modules.py
- test/mpi_download/S0_download_ASDF_MPI.py
- test/mpi_download/loop_for_mpi.py
- test/test.py
Explicit calls to sys.exit() make the software hard to use as a library (vs standalone scripts). They are also unnecessary in most cases. The calls fall into two categories:
- `sys.exit()` calls for rank 0 nodes in mpi. These are just removed since the process will naturally exit anyway.
- `sys.exit()` calls after hitting an error. In this case it's better to raise an exception. This allows the caller to catch/handle it if needed and if not caught the process will exit with an error code anyway.
> Remove uses of sys.exit()

- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/constants.py
- tests/test_asdfstore.py
This PR removes the use of a tmp file (text file) to track already completed computations. Instead, it checks the ASDF file itself in two places:
- Presence of specific station pairs, E.g. `CI.BAK_CI.ARV`
- Presence of a dummy aux data `Progress/done` to mark that all station pairs are complete. This is similar to what the "DONE" last line in the temp file did and prevents having to compute all FFTs even if all CCs are already done.
E.g.
> ASDFCCStore: Remove use of tmp file

- .gitignore
- .vscode/launch.json
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/__init__.py
- src/noisepy/seis/channelcatalog.py
- src/noisepy/seis/main.py
- src/noisepy/seis/noise_module.py
- src/noisepy/seis/scedc_s3store.py
- tests/data/CI_YAQ.xml
- tests/test_channelcatalog.py
- ChannelCatalog implementation that reads XML files obtained from `s3://scedc-pds/FDSNstationXML` for inventory information.
- Moved the channel filtering from S1 into the `SCEDCS3DataStore` to avoid fully loading a large number of channels (>4000), when only a subset (~10) is used
- Updates to the CLI (`main.py`) to use the new channel catalog and take the list of stations to filter on for the `cross_correlation` step.
> XMLStationChannelCatalog implementation

- .vscode/launch.json
- pyproject.toml
- src/noisepy/seis/channelcatalog.py
- src/noisepy/seis/main.py
- src/noisepy/seis/scedc_s3store.py
- src/noisepy/seis/utils.py
- tests/test_channelcatalog.py
- tests/test_scedc_s3store.py
- tests/test_utils.py
- Replace direct filesystem access with `fsspec` to support both S3 and local files
- Update unit tests to verify both local data and S3
- Add debug configuration for S3 case in `launch.json`
Test run:
```
$ noisepy cross_correlate --raw_data_path s3://scedc-pds/continuous_waveforms/2002/2002_002/ --stations "SBC,RIO,DEV,HEC,RLR,SVD,RPV,BAK" --xml_path "s3://scedc-pds/FDSNstationXML/CI/" --freq_norm rma 
2023-05-05 11:04:52,548 INFO scedc_s3store __init__ Init: 1 timespans and 42 channels
2023-05-05 11:05:11,349 INFO S1_fft_cc_MPI _filter_channel_data Picked 20.0 as the closest sampling frequence to 20. Filtered to 21/42 channels
unreadable garbarge 9
it takes  75.59s to process the chunk of 2002-01-02T00:00:00+0000 - 2002-01-03T00:00:00+0000
it takes  75.59s to process step 1 in total …
```
> Support reading directly from S3 buckets

- src/noisepy/seis/S0A_download_ASDF_MPI.py
- src/noisepy/seis/scedc_s3store.py
- tests/test_scedc_s3store.py
Two small changes
- Allow passing a `client_url_key` parameter to the `download` function, with `"SCEDC"` as the defautl.
- A helper for filtering channels in cross correlation, so a lambda is not needed in the common case. 
I.e., instead of:
```
SCEDCS3DataStore(S3_DATA, catalog, lambda c: c.station.name in stations and c.type.name.startswith("BH"))
```
It can be:
```
SCEDCS3DataStore(S3_DATA, catalog, channel_filter(stations, "BH"))
```
> Channel filter helper and S0 client parameter

- .github/workflows/test.yaml
- .vscode/launch.json
- src/noisepy/seis/main.py
- src/noisepy/seis/scedc_s3store.py
- tests/test_scedc_s3store.py
- tutorials/noisepy_scedc_tutorial.ipynb
- Updated the SCEDCS3Store to take an additional date range parameter
- Update CLI (main.py) to take start/end dates for CC
- Updated unit tests 
- Updated tutorials/noisepy_scedc_tutorial.ipynb to use two days of data 
- Added S3 testing during CI
Tested using MPI over 3 days:
```
mpiexec -n 3 noisepy cross_correlate \
--raw_data_path s3://scedc-pds/continuous_waveforms/ \
--xml_path s3://scedc-pds/FDSNstationXML/CI/ \
--ccf_path ~/ccfs3tmp --freq_norm rma --stations "SBC,RIO,DEV" \
--start 2022_02_02 --end 2022_02_05
```
> Support passing a date range to SCEDCS3Store

- .vscode/launch.json
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/utils.py
- tests/test_cli.sh
RFC PR (Request for comments!). We have several places in the code where we measure and log timings. This is an attempt at simplifying things and reducing the amount of code it takes to do this. This PR includes a helper class as well as changes to `S1_fft_cc_MPI.py` to show the usage.
TimeLogger is utility class to measure and log the time spent in code fragments. The basic usage is to call:
```
tlog = TimeLogger()
...
tlog.log(message)
```
This will measure the time between the last time checkpoint and the call to ``log()``. The
checkpoint is updated when:
- ``TimeLogger`` instance is created
- ``log()`` is called
- ``reset()`` is called
Alternatively, an explicit reference start time may be passed when logging: ``log(message, start_time)``. E.g.:
```
start_time = tlog.reset()
sleep(1) …
```
> RFC: TimeLogger helper class

- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/main.py
This is a pre-cursor step to parallelizing the cross-correlation computations. The FFTs/STD and other data about a channel are now put in a data structure (`NoiseFFT`) instead of single arrays. This helps in a few ways:
- The array doesn't have 'holes' if some channel doesn't have data, we just don't store an object for this array. This removes the need for the `fft_flag` array.
- There's less indexing, making the code more readable. E.g. `src_fft.std` vs `fft_std[iiS]`
> Refactor S1 to use a dataclass for FFT data

- .vscode/launch.json
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/main.py
- src/noisepy/seis/scedc_s3store.py
- src/noisepy/seis/stores.py
- tests/test_asdfstore.py
- tests/test_channelcatalog.py
- tests/test_cli.sh
- tests/test_cross_correlation.py
- tests/test_scedc_s3store.py
- tutorials/get_started.ipynb
Changes
- Similar to the change made in S1, S2 no uses the CrossCorrelationDataStore instead of directly accessing the ASDF files.
- Refactored ASDF stores to share functionality between the raw and CC stores
- Add unit tests for the new reading functions in the CC store
- Add a constructor for `Station` to use when lat/lon/elev are not known. Previously `0` and `-1` were inconsistently used as missing values, neither of which was good.
- Fix problem with double initialization of ray.
TODO: Implement a similar store for writing the stacked data
> Use CC store in S2

- .vscode/launch.json
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/asdfstore.py
- tests/test_asdfstore.py
- tests/test_scedc_s3store.py
- tutorials/noisepy_scedc_tutorial.ipynb
This is a refactoring in preparation for writing an ASDFStackStore. This will have very similar functionality to the other ASDF stores, except that the files are names after pairs of stations (e.g. `CI.AVM_CI.AVM.h5`) vs time ranges (`2019_02_01_00_00_00T2019_02_01_12_00_00.h5`). The core part of the refactoring is moving the common functionality up to the `ASDFDirectory` helper class.
> Refactoring of ASDF stores

- pyproject.toml
- src/noisepy/seis/S1_fft_cc_MPI.py
While experimenting with Ray, Dask and plain native ThreadPoolExecutor I found the latter gave comparable performance, with fewer dependencies:
```
2023-06-05 10:33:12,949 INFO utils log TIMING: 2.2965 for get channels
2023-06-05 10:33:13,493 INFO utils log TIMING: 0.5442 for read channel data
2023-06-05 10:33:15,596 INFO utils log TIMING: 2.1025 for preprocess
2023-06-05 10:33:18,824 INFO utils log TIMING: 3.2282 for Compute FFTs
2023-06-05 10:33:24,193 INFO utils log TIMING: 13.5408 for Process the chunk of 2022-01-02T00:00:00+0000 - 2022-01-03T00:00:00+0000
2023-06-05 10:33:24,194 INFO utils log TIMING: 13.5435 for Step 1 in total
```
Reference: https://github.com/mdenolle/NoisePy/pull/117
> Remove ray dependency

- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/channelcatalog.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/utils.py
- tests/data/CI/CI.YAQ.xml
- tests/test_channelcatalog.py
- tests/test_datatypes.py
- Allow for passing a custom format string to build a file name from a `Station`
- In S1, abort if the stations do not have lat/lon/elevation information
- Added unit tests
> Support custom file names in XMLStationChannelCatalog

- .github/workflows/notebooks.yml
- src/noisepy/seis/S0A_download_ASDF_MPI.py
- src/noisepy/seis/S2_stacking.py
Changes:
- Use ThreadPoolExecutor to parallelize without MPI
- Use a single call to `client.get_stations_bulk()` to fetch the inventory instead of 1 call per station/channel
- Don't re-fetch the inventory for each station during download, instead reuse the main inventory downloaded at the beginning
```
2023-06-12 16:08:37,095 INFO S0A_download_ASDF_MPI.download(): downloading step takes 120.01 s
2023-06-12 16:12:03,734 INFO S0A_download_ASDF_MPI.download(): downloading step takes 128.84 s
2023-06-12 16:15:23,021 INFO S0A_download_ASDF_MPI.download(): downloading step takes 127.60 s
```
```
2023-06-12 16:19:12,375 DEBUG utils.log(): TIMING: 13.6195 for Total Download
2023-06-12 16:19:34,644 DEBUG utils.log(): TIMING: 10.7182 for Total Download
2023-06-12 16:19:57,185 DEBUG utils.log(): …
```
> Optimize download step

- .github/actions/setup/action.yaml
- .github/workflows/test.yaml
- README.md
- pyproject.toml
- src/noisepy/seis/S0A_download_ASDF_MPI.py
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/main.py
- src/noisepy/seis/scheduler.py
- tests/test_cli.sh
- tutorials/cli/README.md
Having MPI as a core dependency presented several difficulties. It requires an MPI implementation, which is often platform dependent and takes longer to install. Installing MPI was one of the difficulties people faced on the last workshop. Furthermore, it's typically not required in cloud or single machine deployments.
This PR makes it an optional dependency by:
- Adding a `Scheduler`  abstraction to factor out the MPI/non-MPI details from the main computation
- Making mpi an optional dependency (ie `[mpi]`)
- Adding support for the CLI through a `--mpi` argument
- Updating the CI testing to not require MPI for the bulk of the tests (faster) but adding a specific MPI test
> Make MPI an optional dependency

- pyproject.toml
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/stores.py
- src/noisepy/seis/zarrstore.py
- tests/test_asdfstore.py
- tests/test_ccstores.py
Implementation of a CrossCorrelationStore using Zarr 
Changes:
- Update CrossCorrelationStore interface to be more general
- Move various helper functions from `asdfstore.py` to `stores.py` to use across the two types of store
- Implement ZarrCCStore
- Refactor unit tests to share the testing code between the two stores
TODO:
- Update `plotting_module` to use a CrossCorrelationStore instead of direct `.h5` file access so that CCs stored in Zarr can be plotted
- Update tutorials to use Zarr?
- Update CLI to support Zarr and add this to the test matrix
> ZarrCCStore implementation

- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/stores.py
- tests/test_asdfstore.py
- tests/test_ccstores.py
- tests/test_stackstores.py
- tutorials/get_started.ipynb
- tutorials/noisepy_pnwstore_tutorial.ipynb
- tutorials/noisepy_scedc_tutorial.ipynb
We need to update the plotting functions to use the store abstraction instead of reading ASDF files directly. This will enable using other formats, such as Zarr.
Changes:
- Support read operations on the StackStore
- Add unit tests for StackStore
- Update plotting module functions to use stores
- Update notebooks
> Update plot_substack_cc to use CC store

- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/pnwstore.py
- src/noisepy/seis/scedc_s3store.py
- tutorials/noisepy_pnwstore_tutorial.ipynb
This PR contains some small modifications to the PNWDataStore object. After the modification, the PNWDataStore object now supports:
- channel filter for multiple channel types, e.g., loading HH,EH,BH at the same time
- reading data from multiple network name, e.g., UW, UO, CC, at the same time. The later one is achieved straightforward by modifying DATA path: we replace hardcoded network name to "__", which is the wildcard in the sqlite grammar indicating any two chars. 
See the updated tutorial (noisepy_pnwstore_tutorial.ipynb) for more information. We are doing more tests at this moment.
> Add support for multiple network names and channel type

- pyproject.toml
Prevent inadvertently upgrading to a major version of a dependency
> Add upper bounds to dependency versions

- .github/workflows/precommit.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- pyproject.toml
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/main.py
- src/noisepy/seis/utils.py
- src/noisepy/seis/zarrstore.py
- tests/test_cli.sh
- Adds a `--format zarr|asdf` argument to the CLI
- Additional timing measurement and logging
- Update the test matrix to:
- Include for format (zarr vs asdf)
- Be more sparse. All types of normalization and stacking are tested, but not all combinations, which is overkill
> Support Zarr format from the CLI

- src/noisepy/seis/datatypes.py
- src/noisepy/seis/main.py
- src/noisepy/seis/utils.py
- src/noisepy/seis/zarrstore.py
- tests/test_datatypes.py
Add `storage_options` to ConfigParameters to be able to specify authentication for S3 and other protocols. E.g.:
```
storage_options:
s3:
anon: false
profile: "my_aws_test_profile"
```
> Support for S3 and Zarr

- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/plotting_modules.py
- tests/test_cross_correlation.py
In some datasets (e.g. SCEDC S3 bucket) the data comes in multiple sampling rates and we need a way of selecting one. So the desired sampling rate is passed as a config parameter and we find the  sampling rate available in the data that is the closest (but equal or greater) than the config. Then we use only the data at that exact frequency.
However, in other scenarios we want to use all the data, as long as its above the desired sampling rate. This PR adds a configuration parameter to control this.
It also adds a couple of checks to avoid crashing when there's missing data.
> Add single_freq parameter, bug fixes

- src/noisepy/seis/pnwstore.py
This PR fix the problem that when a day-long mSEED contains too many gaps, the file system could not handle them well.
> Fix PNWDataStore too many files open error

- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/stores.py
- src/noisepy/seis/utils.py
- src/noisepy/seis/zarrstore.py
- tests/test_ccstores.py
- tests/test_utils.py
This changes updates the CrossCorrelationStore interface to read and write all cross-correlations for a station pair at once (i.e. all channels). This allows for more efficient I/O and better parallelization when writing the data. 
Fixes https://github.com/mdenolle/NoisePy/issues/170
> Batch CC reads and writes for all channels

- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/__init__.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/zarrstore.py
There was a bug in the use of `Station` objects as a dictionary key. The class was overriding `__hash__` but not `__eq__`, which resulted in erratic behavior when used as a key.
+ additional logging
> (fix) Fix parallelization of zarr writes

- .github/workflows/precommit.yaml
- .github/workflows/test.yaml
- .vscode/launch.json
- CONTRIBUTING.md
- README.md
- pyproject.toml
Reducing the supported platforms and variability in dependencies to help provide a more consistent experience for noisepy users.
> Limit to Python >=3.10 and pin dependencies

- pyproject.toml
- src/noisepy/seis/S1_fft_cc_MPI.py
- src/noisepy/seis/S2_stacking.py
- src/noisepy/seis/channelcatalog.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/hierarchicalstores.py
- src/noisepy/seis/main.py
- src/noisepy/seis/numpystore.py
- src/noisepy/seis/scedc_s3store.py
- src/noisepy/seis/stores.py
- src/noisepy/seis/tiledb.py
- src/noisepy/seis/utils.py
- src/noisepy/seis/zarrstore.py
- tests/test_ccstores.py
- Implementation of a numpy/tar.gz store
- Refactoring to share common code between Numpy and Zarr stores
- Parallelization of loading for SCEDC channel data
- Misc. fixes
[Test job on AWS](https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/fargate/detail/c71b1f33-a75d-4303-8b1f-893fc6e2cf05)
[Output bucket](https://s3.console.aws.amazon.com/s3/buckets/carlosgjs-noisepy?region=us-west-2&prefix=test_batch/CCF_11_sta_2022_02_05_numpy/&showversions=false)
Reading results:
```
>>> from noisepy.seis.numpystore import NumpyCCStore
>>> s = NumpyCCStore("s3://carlosgjs-noisepy/test_batch/CCF_11_sta_2022_02_05_numpy/", mode="r")
2023-09-08 15:12:18,969 8336924160 INFO numpystore.__init__(): store creating at s3://carlosgjs-noisepy/test_batch/CCF_11_sta_2022_02_05_numpy/, …
```
> Fixes/refactoring from large scale tests on AWS/S3

- .github/workflows/release.yaml
- Dockerfile
There's a problem building the docker container on arm64. It fails to build the wheel for `numcodecs` with the errors:
```
gcc: error: unrecognized command-line option ‘-msse2’ 
gcc: error: unrecognized command-line option ‘-mavx2’
```
Disabling arm64 for now to unblock since all cloud use cases are based on amd64.
> Disable arm64 container build

- src/noisepy/seis/channelcatalog.py
Before (from Marine's run) ~10 mins:
```
2023-09-13 23:10:12,725 140060162046848 INFO utils.log_raw(): TIMING CC Main: 591.1919 secs. for get 756 channels
```
After (test run) ~2.8 mins:
```
2023-09-14 23:17:17,047 140072190446464 INFO utils.log_raw(): TIMING CC Main: 167.7949 secs. for get 753 channels
```
> Fix caching in XMLChannelCatalog

- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/plotting_modules.py
- tutorials/noisepy_scedc_tutorial.ipynb
- Revert opening the cc_store in `"w"` mode and validate that only `"a"` or `"r"` are used
- Use StackMethod enum instead of string value
- Update `plot_all_moveout` to use new stack store interface
> Fixes to SCEDC tutorial

- .github/workflows/release.yaml
- script/gen_req.py
When testing the source distribution install, only install noisepy from source. Installing **all** from source it's unnecessary and more unstable. E.g. recently `hatchling==1.18.0` was failing to install from source.
The change to `gen_req.py` is opportunistic since it was missed in the last AWS PR and is only used in dev testing.
> Fix source dist testing

- .github/workflows/test.yaml
- integration_tests/cc_stack_test.py
- src/noisepy/seis/correlate.py
- src/noisepy/seis/stack.py
- tests/test_stack.py
- Sort timespans/node pairs to ensure work is properly distributed across nodes
- Better error/summary report for stacking
- Release memory more aggressively in CC
> Stacking and CC memory fixes

- .github/workflows/notebooks.yml
- .github/workflows/test.yaml
- src/noisepy/seis/numpystore.py
- src/noisepy/seis/utils.py
- tests/test_channel_filter_store.py
- tests/test_utils.py
- Fix to `utils.get_filesystem` for Windows
- Escape the prefix used in a regex since on windows it can contain backslashes, which `re` will interpret as escape sequences.
- Run unit tests on Windows
Previous code was only working on posix paths, because the url scheme for `"/some/path"` is `""`, which to fsspec means "file" (local). But with a windows path like `"c:\some\path"`, the url scheme becomes `"c"`, which fsspec doesn't understand.
> Run on windows

- src/noisepy/seis/asdfstore.py
- src/noisepy/seis/correlate.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/hierarchicalstores.py
- src/noisepy/seis/numpystore.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/stack.py
- src/noisepy/seis/stores.py
- src/noisepy/seis/zarrstore.py
- tests/test_ccstores.py
- tests/test_cli.sh
- tests/test_hierarchicalstores.py
- tests/test_stack.py
- tests/test_stackstores.py
- tests/utils.py
- tutorials/noisepy_scedc_tutorial.ipynb
See discussion: https://github.com/noisepy/NoisePy/discussions/229
Summary of changes:
- Redefined CrossCorrelationStore and StackStore to be more consistent
- `read_correlations` and `read_stacks` are now both `read`
- changes the order of parameters in the `contains()` methods
- Changed the implementations of the numpy and zarr stores to use the hierarchy described in the discussion. These now share the bulk of the implementation for both CC and Stack.
- Implemented an efficient caching of the cc/stack store directory
> Changes to store interfaces and implementations

- CONTRIBUTING.md
- integration_tests/cc_stack_test.py
- src/noisepy/seis/__init__.py
- src/noisepy/seis/correlate.py
- src/noisepy/seis/datatypes.py
- src/noisepy/seis/hierarchicalstores.py
- src/noisepy/seis/main.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/stack.py
- tests/test_cross_correlation.py
- tests/test_datatypes.py
- tests/test_hierarchicalstores.py
- tests/test_stack.py
- tests/test_stackstores.py
- tests/utils.py
- tutorials/get_started.ipynb
- tutorials/noisepy_pnwstore_tutorial.ipynb
- tutorials/noisepy_scedc_tutorial.ipynb
- tutorials/plot_stacks.ipynb
- Standardize and validate dates to be UTC
- Rename `stack()` function to `stack_cross_correlations()` to avoid name conflict with the `stack.py` module. @mdenolle another option is to rename the module. E.g to `stacking.py` and keep the function as `stack()`. WDYT?
- Parallelize data loading in `plot_all_moveout `. 
- RFC: Support sub-sampling a portion of the station pairs for faster plotting (see comment inline)
- Add simple notebook for plotting existing stacked data
- Fix loading of config from S3 bucket
- Change default format to NUMPY
> Stacking fixes/improvements

- src/noisepy/seis/main.py
- tests/test_main.py
Fixes issue #233 
Also refactor the running of stack/cc/download in main to removes reduntant/duplicated code. The code to load/save config, error handling and saving of the logs is now in one place.
> Allow reading config from S3, refactor main

- .github/actions/setup/action.yaml
- src/noisepy/seis/correlate.py
- src/noisepy/seis/hierarchicalstores.py
- src/noisepy/seis/main.py
- src/noisepy/seis/utils.py
- tests/test_hierarchicalstores.py
- Fix/refactor retry logic for S3 IO
- Log which station pairs failed in CC (similar to stacking)
- Avoid repeatedly checking the S3 bucket for existing pairs when it's empty
> Better retries for IO, logging

- src/noisepy/seis/datatypes.py
- src/noisepy/seis/numpystore.py
- src/noisepy/seis/plotting_modules.py
- src/noisepy/seis/stores.py
- src/noisepy/seis/zarrstore.py
- tests/test_stackstores.py
- tutorials/get_started.ipynb
- tutorials/noisepy_pnwstore_tutorial.ipynb
- tutorials/noisepy_scedc_tutorial.ipynb
- tutorials/plot_stacks.ipynb
- Moved the parallel data loading code from `plot_all_moveout` to a helper on the store object
- Updated parameters and notebooks
- Unrelated: fixed lint about using `isinstance` instead of `type(...)==`
This makes it easier for someone to experiment what to plot. As a simple example
> refactor: Decouple data loading from plot_all_moveout

- src/noisepy/seis/datatypes.py
- src/noisepy/seis/noise_module.py
- tests/test_ccstores.py
The CC parameters were failing to save to ASDF after the conversion of cc_method to an enum. Fixed the problem and updated the test to use the types used at runtime.
> fix: CC method serializaton for ASDF stores

- .github/workflows/test.yaml
- README.md
- src/noisepy/seis/main.py
- tests/test_cli.sh
- tests/test_main.py
This PR adds a `--stop-on-error` flag to the CLI. On big jobs we typically want to continue even in the presence of some errors. E.g. A hand-full of CC pairs fails to compute out of 50k. However, during integration testing we want to make sure we detect any failures.
The tests on this PR are expected to fail until #261 is merged.
> Add --stop-on-error flag for testing

- src/noisepy/seis/pnwstore.py
@kuanfufeng pointed out that the detrend and taper in the data client is not necessary and may create unwanted discontinuities in the merged stream. Detrending and/or taper will be implemented in the `preprocess_raw` function, so it's not the job of raw data store. I am removing these two lines of codes.
> Update PNWstore reader

- src/noisepy/seis/plotting_modules.py
This commit will fix minor bugs in 3 plotting functions (plot_substack_cc, plot_all_moveout, plot_all_moveout_1D_1comp) in the plotting_modules.py. Before and after plots as well as more detailed explanations are attached.
[PR_plotfix_comparison_Yantao.pdf](https://github.com/noisepy/NoisePy/files/13847736/PR_plotfix_comparison_Yantao.pdf)
> Fix: incorrect plotting function behaviors in plotting_modules.py

- integration_tests/cc_stack_test.py
- src/noisepy/seis/channel_filter_store.py
- src/noisepy/seis/main.py
- src/noisepy/seis/scedc_s3store.py
- tests/test_scedc_s3store.py
- tutorials/noisepy_datastore.ipynb
- tutorials/noisepy_ncedc_tutorial.ipynb
- tutorials/noisepy_pnwstore_tutorial.ipynb
- tutorials/noisepy_scedc_tutorial.ipynb
- tutorials/run_mpi_scedc.ipynb
This PR merges the redundancy of channel filter previously in [main.py](https://github.com/noisepy/NoisePy/blob/773b90bb7609a90f62dd4eae5b6fd2ab8981b761/src/noisepy/seis/main.py#L127-L139) and another version in [SCEDCS3DataStore](https://github.com/noisepy/NoisePy/blob/773b90bb7609a90f62dd4eae5b6fd2ab8981b761/src/noisepy/seis/scedc_s3store.py#L22-L35). The version in the main.py is preserved so that the notebook version conform to the CLI version. In that case, channel type should be explicitly written, e.g., "HHE", "HHN", "HHZ". No wildcard is implicitly assumed.
This PR fixes the issue #195.
> Resolving channel filter redundancy

- .github/workflows/release.yaml
> chore: update PyPi publishing to use trusted publisher 

- src/noisepy/seis/utils.py
- tests/test_datatypes.py
- tests/test_utils.py
The iml file has been added [here](https://github.com/noisepy/NoisePy/blob/main/configs/default.yml). Moreover, the raw [HTTPS url](https://raw.githubusercontent.com/noisepy/NoisePy/main/configs/default.yml) can read by ConfigParameters.
This should work now.
```python
config = ConfigParameters.load_yaml("https://raw.githubusercontent.com/noisepy/NoisePy/main/configs/default.yml")
```
This should fix #295
> feat: add https filesystem and support load yml from url

- .gitignore
- integration_tests/cc_stack_test.py
- pyproject.toml
- src/noisepy/seis/main.py
- tests/test_cross_correlation.py
- tutorials/_toc.yml
- tutorials/noisepy_compositestore_tutorial.ipynb
- tutorials/noisepy_datastore.ipynb
- tutorials/noisepy_ncedc_tutorial.ipynb
- tutorials/noisepy_scedc_tutorial.ipynb
- tutorials/run_mpi_scedc.ipynb
We will use the updated io package, where the rename of `scedc_s3store` is simplified to `s3store`.
> chore: update to new version dependency and use s3store

- pyproject.toml
The scipy made a new release April 2 2024 and moved the hanning function. This raised issues to our package. Thus, we need to restrict scipy to 1.12.0.
> fix: update scipy dependencies

- src/noisepy/monitoring/attenuation_utils.py
- src/noisepy/monitoring/monitoring_utils.py
- tutorials/monitoring/attenuation_singlestation.ipynb
- tutorials/monitoring/monitoring_demo.ipynb
This PR 
- add config parameters for attenuation scripts and update the notebook accordingly 
- add a post-process notebook for monitoring tasks
> Update config parameter and notebooks for attenuation monitoring

- src/noisepy/seis/noise_module.py
In noise_module.py, we replace interpolate with resample for downsampling.
> replace interpolate with resample
